services:
  app:
    build: .
    container_name: crawlagent-app
    ports:
      - "80:8000"
      - "443:8000"
      - "8000:8000"
    environment:
      - PYTHON_ENV=production
      - AWS_ENDPOINT_URL_IAM=https://fly.iam.storage.tigris.dev
      - AWS_ENDPOINT_URL_S3=https://fly.storage.tigris.dev
      - AWS_REGION=auto
      - REDIS_MAX_RETRIES=100
      - REDIS_RETRY_DELAY_SEC=3
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DISPLAY=:99
      - PYTHONPATH=/app
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips="*" --ws websockets
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G

  worker:
    build: .
    container_name: crawlagent-worker
    environment:
      - PYTHON_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DISPLAY=:99
    command: celery -A celery_app.celery_app worker --loglevel=info -E
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G

  exporter:
    build: .
    container_name: crawlagent-celery-exporter
    ports:
      - "9808:9808"
    environment:
      - PYTHON_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: ./celery-exporter --broker-url=${CELERY_BROKER_URL} --port=9808 --retry-interval=5 --host=0.0.0.0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

  redis:
    image: redis:alpine
    container_name: crawlagent-redis
    ports:
      - "6379:6379"
